
name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild
      run: xcodebuild clean build -project ShortKey.xcodeproj -scheme ShortKey -destination "platform=iOS Simulator,name=iPhone 11 Pro"
